# Generated by Django 5.1.7 on 2025-04-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='activo',
        ),
    ]
