# Generated by Django 5.1.7 on 2025-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cupos',
            field=models.IntegerField(default=0),
        ),
    ]
