# Generated by Django 5.1.7 on 2025-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_cupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='metodo_pago',
            field=models.CharField(choices=[('link', 'Link de pago'), ('efectivo', 'Pago en efectivo en estudio')], default='link', max_length=10),
        ),
    ]
