# Generated by Django 5.1.7 on 2025-05-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
