# Generated by Django 5.1.7 on 2025-05-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_modificado_alter_cliente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='reactivaciones',
        ),
        migrations.DeleteModel(
            name='Reactivacion',
        ),
    ]
