# Generated by Django 5.1.7 on 2025-05-14 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_fecha_alta_alter_cliente_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
