# Generated by Django 5.1.7 on 2025-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
