# Generated by Django 5.1.7 on 2025-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_evento_metodo_pago_evento_pago_en_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_pago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
