# Generated by Django 5.1.7 on 2025-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_evento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionevento',
            name='apellido',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
