# Generated by Django 5.1.7 on 2025-04-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_inscripcionevento_apellido_inscripcionevento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
