# Generated by Django 5.1.7 on 2025-04-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_remove_inscripcionevento_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionevento',
            name='email',
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='mail',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
