# Generated by Django 5.1.7 on 2025-04-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_inscripcionevento_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionevento',
            old_name='mail',
            new_name='email',
        ),
    ]
