# Generated by Django 5.1.7 on 2025-04-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='evento',
            name='pago_en_estudio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='pago_enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
