# Generated by Django 5.1.7 on 2025-04-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('eventos', '0010_alter_evento_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionevento',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='inscripcionevento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
