# Generated by Django 5.1.7 on 2025-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_fecha_alta_cliente_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
