# Generated by Django 5.1.7 on 2025-05-14 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_cliente_reactivaciones_delete_reactivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('regular', 'Regular'), ('eventual', 'Eventual')], default='regular', max_length=10),
        ),
    ]
