# Generated by Django 5.1.7 on 2025-05-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_confirmacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
