# Generated by Django 5.1.7 on 2025-04-25 22:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_configuracion_dias_habilitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='dias_habilitados',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=52),
        ),
    ]
