# Generated by Django 5.1.7 on 2025-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
