# Generated by Django 5.1.7 on 2025-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('ingreso', models.DateField()),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/')),
                ('mostrar_en_web', models.BooleanField(default=False)),
            ],
        ),
    ]
