# Generated by Django 5.1.7 on 2025-04-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
