# Generated by Django 5.1.7 on 2025-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mostrar_en_web',
            field=models.BooleanField(default=True),
        ),
    ]
