# Generated by Django 5.1.7 on 2025-04-25 22:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_configuracion_mensaje_whatsapp_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='dias_habilitados',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default=['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sabado'], max_length=52),
        ),
    ]
