# Generated by Django 5.1.7 on 2025-04-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_alter_configuracion_dias_habilitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='horario_domingo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='horario_domingo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
