# Generated by Django 5.1.7 on 2025-04-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(default='Estudio', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('maps', models.URLField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(blank=True, max_length=255)),
                ('texto_hero', models.TextField(blank=True)),
            ],
        ),
    ]
