# Generated by Django 5.1.7 on 2025-04-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='horario',
            new_name='hohorario_semana',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='horario_sabado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
