# Generated by Django 5.1.7 on 2025-04-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_rename_horario_configuracion_hohorario_semana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='hohorario_semana',
            new_name='horario_semana',
        ),
    ]
