# Generated by Django 5.1.7 on 2025-04-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_rename_hohorario_semana_configuracion_horario_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='cuit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
