# Generated by Django 5.1.7 on 2025-04-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_remove_configuracion_horario_sabado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mensaje_whatsapp_evento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mensaje_whatsapp_plan',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
